### ISSUE TITLE
Dont know why this code is not working

### ISSUE THREAD

**Issue by Amachuarori** [pirple/Python-Is-Easy#3]
def ListAdd():
    a = int(input())
    myUniqueList.append(a)
    print (myUniqueList)

**Comment by Amachuarori** [comment]
myUniqueList = []
myLeftovers = []

def ListAdd():
    a = int(input())
    if a >= 15:
        myUniqueList.append(a)
        print(myUniqueList)
    else: 
        myLeftovers.append(a)
        print(myLeftovers)
    
    And this part too

**Comment by littlebuddha16** [comment]
Things you need to look.


  1.  Did you define a list called myUniqueList before calling the function?
  2.  Check out the whitespaces after def ListAdd()

Regards,
Kiran
________________________________

**Comment by littlebuddha16** [comment]
Try this

myUniqueList = []
myLeftovers = []

def ListAdd():
    a = int(input())
    if a >= 15:
        myUniqueList.append(a)
        print(myUniqueList)
    else:
        myLeftovers.append(a)
        print(myLeftovers)

​Regards,
Kiran
________________________________

**Comment by Amachuarori** [comment]
thanks, but it's still not working,  i tried it before. It's just  printing a number i've written(

**Comment by Amachuarori** [comment]
PS C:\Users\Admin\Desktop\python-projects> 15
15

**Comment by Amachuarori** [comment]
whithout an if and functions it prints a list with written number

**Comment by littlebuddha16** [comment]
It's working fine for me.

[cid:7459b5d8-5d09-4975-b4bb-424419bcd649]
________________________________

**Comment by Amachuarori** [comment]
well, i forgot to call the function, lol
